name: pi
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0=mkl
  - bleach=4.0.0
  - bottleneck=1.3.2
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - cffi=1.14.6
  - click=8.0.1
  - colorama=0.4.4
  - dataclasses=0.8
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - flask=1.1.2
  - flask-sqlalchemy=2.5.1
  - git=2.34.1
  - greenlet=1.1.1
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - itsdangerous=2.0.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - libpng=1.6.37
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.3
  - numexpr=2.7.3
  - openssl
  - packaging=21.0
  - pandas=1.3.2
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - pycparser=2.20
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.10.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - waitress=2.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - zipp=3.5.0
  - zlib=1.2.11
  - pip:
    - absl-py==0.14.1
    - astunparse==1.6.3
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - clang==5.0
    - deepface==0.0.69
    - filelock==3.3.0
    - flatbuffers==1.12
    - gast==0.4.0
    - gdown==4.0.2
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.41.0
    - h5py==3.1.0
    - idna==3.2
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - mtcnn==0.1.1
    - mysqlclient==2.0.3
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - pillow==8.3.2
    - protobuf==3.18.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pymysql==1.0.2
    - pysocks==1.7.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - retina-face==0.0.5
    - rsa==4.7.2
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.0
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - tqdm==4.62.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.7
    - wrapt==1.12.1
